database/models/cliente.py
from peewee import Model, CharField, DateTimeField
from database.dataBase import db
import datetime

class Cliente(Model):
    nome = CharField()
    email = CharField()
    data_criacao = DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db

main.py
from flask import Flask
from configuration import configure_all

#Inicializacao
app = Flask(__name__)

configure_all(app)

#execucao
app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.models.cliente import Cliente

cliente_route = Blueprint("cliente", __name__)

"""procurar cliente no banco de dados"""
@cliente_route.route('/')
def lista_clientes():
    clientes = Cliente.select()
    return render_template('lista_clientes.html', clientes=clientes)


"""inserir cliente no banco de dados"""
@cliente_route.route('/', methods=['POST'])
def inserir_clientes():

    data = request.json

    novo_usuario = Cliente.create(
        nome = data['nome'],
        email = data['email'],
    )

    return render_template('item_cliente.html', cliente=novo_usuario)


"""cadastro de um cliente"""
@cliente_route.route('/new')
def form_clientes():
    return render_template('form_clientes.html')


"""detalhes de um cliente"""
@cliente_route.route('/<int:cliente_id>')
def detalhe_clientes(cliente_id):

    cliente = Cliente.get_by_id(cliente_id)
    return render_template('detalhe_clientes.html', cliente=cliente)


"""formulario para editar um cliente"""
@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_clientes(cliente_id):

    cliente = Cliente.get_by_id(cliente_id)

    return render_template('form_clientes.html', cliente = cliente)


"""atualizar informacao de um cliente"""
@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def update_clientes(cliente_id):
    #obter dados do formulario de edicao
    data = request.json
    #obter usuario pelo id
    cliente_editado = Cliente.get_by_id(cliente_id)
    cliente_editado.nome = data['nome']
    cliente_editado.email = data['email']
    cliente_editado.save()

    return render_template('item_cliente.html', cliente=cliente_editado)


"""deletar informacoes de um cliente"""
@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_clientes(cliente_id):
    cliente = Cliente.get_by_id(cliente_id)
    cliente.delete_instance()
    return{'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/detalhe_clientes.html
<ul>
   <li>ID: {{cliente.id}} </li> 
   <li>NOME: {{cliente.nome}} </li>
   <li>EMAIL: {{cliente.email}} </li>
</ul> 

templates/form_clientes.html
<form class="c-form" 
      {% if cliente %}
        action="{{url_for('cliente.update_clientes', cliente_id=cliente.id) }}" 
      {% else %}
        action="{{url_for('cliente.inserir_clientes') }}"
      {% endif %}

      method="{% if cliente %}PUT{% else %}POST{% endif %}"

      {% if cliente %}

        c-swap="#cliente-{{cliente.id}}"

      {% else %}

        c-append="#lista-clientes"

      {% endif %}

      c-reload-container="true">      

    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome"
      {% if cliente %}value="{{ cliente.nome }}"{% endif %}>
    </div>

    <div class="mb-3">
        <label id="label-target" class="form-label">Email</label>
        <input type="text" class="form-control" name="email"
        {% if cliente %}value="{{ cliente.email }}"{% endif %}>
    </div>

    <button type="submit" class="btn btn-primary">
      {% if cliente %}Salvar{% else %}Criar{% endif %}
    </button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
  </head>
  <body>

    <div class="container">

        <h1>Gestao de clientes</h1>


        <!-- Formulario para adicionar clientes-->
        <div id="form_cliente" 
          c-container="{{ url_for('cliente.form_clientes') }}"></div>

        <hr></hr>
        <!--Lista de clientes-->
        <h2>Lista de clientes</h2>

        <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>

    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir-cliente">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='cru.js') }}"></script>

  </body>
</html>

templates/item_cliente.html
<tr class ="cliente-{{ cliente.id }}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" 
            c-get="{{ url_for('cliente.detalhe_clientes', cliente_id=cliente.id) }}"
            c-target="#exibir-cliente"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
                Ver
        </button>

        <button class="btn btn-primary" 
            c-get="{{ url_for('cliente.form_edit_clientes', cliente_id=cliente.id) }}"
            c-target="#form_cliente">
                Editar
        </button>

        <button class="btn btn-danger" 
            c-delete="{{ url_for('cliente.delete_clientes', cliente_id=cliente.id )}}"
            c-remove-closest="tr">
                Deletar
        </button>
    </td>
  </tr>

templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Acoes</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">

    {% for cliente in clientes %}

      {% include 'item_cliente.html' %}

    {% endfor %}

    </tbody>
  </table>